# Generated by Django 6.0.4 on 2026-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Bekleniyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('paused', 'Duraklatıldı')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='0-100 arası yüzde')),
                ('total_items', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('error_rate', models.CharField(default='0%', max_length=10)),
                ('robot', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Süreç',
                'verbose_name_plural': 'Süreçler',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('queue_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Bekleniyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kuyruk',
                'verbose_name_plural': 'Kuyruk Öğeleri',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Aylık'), ('weekly', 'Haftalık'), ('daily', 'Günlük'), ('performance', 'Performans'), ('audit', 'Denetim')], max_length=50)),
                ('content', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robot_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Bakım')], default='offline', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('robot', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('once', 'Bir Kez'), ('hourly', 'Saatlik'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], max_length=20)),
                ('time', models.TimeField()),
                ('day', models.CharField(blank=True, help_text='Haftalık/Aylık için', max_length=20, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zamanlama',
                'verbose_name_plural': 'Zamanlamalar',
                'ordering': ['name'],
            },
        ),
    ]
