# Generated by Django 6.0.4 on 2026-04-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('smtp_host', models.CharField(max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(max_length=150)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Hesabi',
                'verbose_name_plural': 'Mail Hesaplari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=120)),
                ('bot_token', models.CharField(max_length=255)),
                ('default_parse_mode', models.CharField(blank=True, choices=[('', 'Yok'), ('HTML', 'HTML'), ('Markdown', 'Markdown'), ('MarkdownV2', 'MarkdownV2')], default='', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Botu',
                'verbose_name_plural': 'Telegram Botlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('chat_id', models.CharField(max_length=80, unique=True)),
                ('owners', models.CharField(blank=True, help_text='Surec sahibi kisiler veya ekip adlari', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.telegrambot')),
            ],
            options={
                'verbose_name': 'Telegram Grubu',
                'verbose_name_plural': 'Telegram Gruplari',
                'ordering': ['name'],
            },
        ),
    ]
