# Generated by Django 6.0.4 on 2026-04-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mailaccount_telegrambot_telegramgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAP Süreci',
                'verbose_name_plural': 'SAP Süreçleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SapProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('sap_fill', 'SAP Ekranı Doldur (Şablon)'), ('sap_run', 'F8 – Çalıştır'), ('sap_wait', 'Ekranı Bekle'), ('sap_scan', 'Derin Tarama'), ('sap_action', 'Aksiyon Yap'), ('sap_close', 'SAP Kapat'), ('loop_next', 'Döngü – Sonraki Kayıt')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.sapprocess')),
            ],
            options={
                'verbose_name': 'SAP Adımı',
                'verbose_name_plural': 'SAP Adımları',
                'ordering': ['order'],
            },
        ),
    ]
