# Generated by Django 6.0.4 on 2026-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sap_process_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('protocol', models.CharField(choices=[('sftp', 'SFTP'), ('ftp', 'FTP'), ('ftps', 'FTPS')], default='sftp', max_length=10)),
                ('host', models.CharField(max_length=180)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('remote_base_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FTP Hesabi',
                'verbose_name_plural': 'FTP Hesaplari',
                'ordering': ['name'],
            },
        ),
    ]
