# Generated by Django 6.0.4 on 2026-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ftp_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapprocessstep',
            name='step_type',
            field=models.CharField(choices=[('sap_fill', 'SAP Ekranı Doldur (Şablon)'), ('sap_run', 'F8 – Çalıştır'), ('sap_wait', 'Ekranı Bekle'), ('sap_scan', 'Derin Tarama'), ('sap_action', 'Aksiyon Yap'), ('ftp_list', 'FTP Listele'), ('ftp_download', 'FTP İndir'), ('ftp_upload', 'FTP Yükle'), ('sap_close', 'SAP Kapat'), ('loop_next', 'Döngü – Sonraki Kayıt')], max_length=50),
        ),
    ]
