# Generated by Django 6.0.4 on 2026-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sapprocessstep_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapprocess',
            name='flow_config',
            field=models.JSONField(blank=True, default=dict, help_text='Canvas layout: nodes ve connections'),
        ),
    ]
