# Generated by Django 6.0.4 on 2026-04-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_telegrambotmenu_telegrambotbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapprocess',
            name='sap_retry_enabled',
            field=models.BooleanField(default=True, help_text='SAP bağlantısı yoksa periyodik tekrar dene'),
        ),
        migrations.AddField(
            model_name='sapprocess',
            name='sap_retry_interval_minutes',
            field=models.PositiveIntegerField(default=10, help_text='SAP bağlantı denemeleri arası bekleme (dakika)'),
        ),
        migrations.AddField(
            model_name='sapprocess',
            name='sap_retry_max_duration_minutes',
            field=models.PositiveIntegerField(default=180, help_text='Toplam SAP bağlantı bekleme süresi (dakika). 0 = sınırsız'),
        ),
        migrations.AlterField(
            model_name='sapprocessstep',
            name='step_type',
            field=models.CharField(choices=[('sap_fill', 'SAP Ekranı Doldur (Şablon)'), ('sap_run', 'F8 – Çalıştır'), ('sap_wait', 'Ekranı Bekle'), ('sap_scan', 'Derin Tarama'), ('sap_action', 'Aksiyon Yap'), ('sap_key_press', 'Tuşa Bas (Klavye)'), ('sap_select_option', 'Radio/Checkbox Seç'), ('sap_fill_input', 'Input Doldur'), ('convert_sap_export', 'SAP Export Dönüştür (XLSX)'), ('windows_dialog_action', 'Windows Popup İşle'), ('windows_scan_dialogs', 'Windows Popup Tanı (Diagnostic)'), ('sap_popup_decide', 'Popup Karar Ver'), ('sap_branch_no_data_guard', 'Şube Veri Kontrolü (Grid Yoksa Sonraki Şube)'), ('sap_press_button', 'SAP Butonuna Bas'), ('sap_select_row', 'Satır Seç (Grid)'), ('ftp_list', 'FTP Listele'), ('ftp_download', 'FTP İndir'), ('ftp_upload', 'FTP Yükle'), ('sap_close', 'SAP Kapat'), ('show_message', 'Mesaj Göster'), ('excel_loop_next', 'Excel Satır Sonraki'), ('run_process', 'Süreç Çalıştır (Alt Süreç)'), ('loop_next', 'Döngü – Sonraki Kayıt'), ('if_else', 'IF / ELSE'), ('if_end', 'IF Sonu'), ('loop_generic', 'Döngü (Generic)'), ('py_script', 'Python Script Çalıştır'), ('excel_row_log', 'Satır Sonucu Yaz'), ('send_report_mail', 'Rapor Oluştur ve Mail Gönder')], max_length=50),
        ),
    ]
