# Generated by Django 6.0.4 on 2026-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sapprocess_sap_retry_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='allowed_user_ids',
            field=models.TextField(blank=True, help_text="İzinli Telegram numerik user ID'leri. Her satıra bir ID veya virgülle ayrılmış. Boş bırakılırsa kimse butonları kullanamaz (kapalı bot)."),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='webhook_registered_url',
            field=models.CharField(blank=True, help_text="Telegram tarafına en son kayıt edilen webhook URL'i (bilgi amaçlı).", max_length=500),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text="Telegram webhook URL'inde kullanılan rastgele güvenlik anahtarı. Boş bırakılırsa otomatik üretilir.", max_length=64),
        ),
    ]
