# Generated by Django 6.0.4 on 2026-04-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_telegrambot_allowed_user_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ajanin sabit kimligi (robot-01 gibi)', max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('token_hash', models.CharField(help_text='Ajan kimlik dogrulama token hash degeri', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('busy', 'Mesgul'), ('maintenance', 'Bakim')], default='offline', max_length=20)),
                ('machine_name', models.CharField(blank=True, max_length=120)),
                ('host_name', models.CharField(blank=True, max_length=180)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('os_user', models.CharField(blank=True, max_length=120)),
                ('agent_version', models.CharField(blank=True, max_length=40)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_startup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robot Ajanı',
                'verbose_name_plural': 'Robot Ajanları',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RobotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('run_sap_process', 'SAP Süreci Çalıştır'), ('run_command', 'Komut Çalıştır')], default='run_sap_process', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Kuyrukta'), ('dispatched', 'Ajan Tarafinda Alindi'), ('running', 'Calisiyor'), ('succeeded', 'Basarili'), ('failed', 'Basarisiz'), ('canceled', 'Iptal')], default='queued', max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_jobs', to='core.sapprocess')),
                ('target_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.robotagent')),
            ],
            options={
                'verbose_name': 'Robot İşi',
                'verbose_name_plural': 'Robot İşleri',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='core_robotj_status_5cff80_idx'), models.Index(fields=['target_agent', 'status'], name='core_robotj_target__14b09b_idx')],
            },
        ),
    ]
