# Generated by Django 6.0.4 on 2026-04-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_robotagent_robotjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotAgentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('release_notes', models.TextField(blank=True)),
                ('download_url', models.CharField(blank=True, max_length=600)),
                ('checksum_sha256', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Robot Ajan Release',
                'verbose_name_plural': 'Robot Ajan Release Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='robotagent',
            name='desired_version',
            field=models.CharField(blank=True, help_text='Bu ajan için hedef EXE sürümü', max_length=40),
        ),
        migrations.CreateModel(
            name='RobotAgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.robotagent')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.robotjob')),
            ],
            options={
                'verbose_name': 'Robot Ajan Event',
                'verbose_name_plural': 'Robot Ajan Event Kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='core_robota_agent_i_d1e941_idx'), models.Index(fields=['level', 'created_at'], name='core_robota_level_03ec27_idx')],
            },
        ),
    ]
