# Generated by Django 6.0.4 on 2026-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_robotagentrelease_robotagent_desired_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotagentrelease',
            name='install_command',
            field=models.CharField(blank=True, help_text='Ajan güncelleme için çalıştırılacak komut şablonu', max_length=800),
        ),
        migrations.AddField(
            model_name='robotagentrelease',
            name='setup_file',
            field=models.CharField(blank=True, help_text='Sunucuda saklanan setup exe yolu', max_length=500),
        ),
    ]
