# Generated by Django 6.0.4 on 2026-04-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_robotagentrelease_install_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicProcessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('frequency', models.CharField(choices=[('interval', 'Interval (dakika)'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='daily', max_length=20)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('weekdays', models.CharField(blank=True, help_text='0-6 arası haftanın günleri (virgülle), 0=Pazartesi', max_length=32)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_schedules', to='core.sapprocess')),
                ('target_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_schedules', to='core.robotagent')),
            ],
            options={
                'verbose_name': 'Periyodik Süreç Planı',
                'verbose_name_plural': 'Periyodik Süreç Planları',
                'ordering': ['enabled', 'next_run_at', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='periodicprocessschedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='core_periodi_enabled_01a67d_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicprocessschedule',
            index=models.Index(fields=['frequency'], name='core_periodi_frequen_d90fd8_idx'),
        ),
    ]
