# Generated by Django 6.0.4 on 2026-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_periodicprocessschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicprocessschedule',
            name='maintenance_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodicprocessschedule',
            name='maintenance_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodicprocessschedule',
            name='overlap_buffer_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='periodicprocessschedule',
            name='prevent_overlap',
            field=models.BooleanField(default=True),
        ),
    ]
