from django.urls import path

from .views import (
    agent_check_update, agent_heartbeat, agent_job_update, agent_log_event, agent_process_definition, agent_pull_job, agent_register, agent_run_process, agent_run_process_status,
    dashboard, ftp_accounts_manage, help_center, help_media_upload, mail_accounts_manage, processes, queues, reports, robots,
    robot_agent_delete, robot_agent_event_list, robot_agent_status, robot_agent_upsert, robot_cancel_job, robot_control_center,
    robot_build_install_package, robot_build_setup_exe, robot_dispatch_job, robot_job_list, robot_release_deploy, robot_release_download, robot_release_download_package, robot_release_list, robot_release_save, robot_set_desired_version,
    sap_scan, sap_apply, sap_run,
    sap_template_list, sap_template_get, sap_template_save, sap_template_delete,
    sap_process_list, sap_process_builder, sap_process_delete,
    sap_process_step_save, sap_process_rename, sap_process_backup, sap_process_runtime_settings_save, sap_process_runtime_control, sap_process_runtime_status, sap_process_scan_buttons, sap_process_scan_selectables, sap_process_scan_inputs, sap_process_scan_windows_dialogs, sap_process_scan_screens, sap_process_scan_grids, sap_process_scan_popups, sap_process_excel_browse, sap_process_excel_sheets, sap_process_excel_columns, sap_process_run_preview,
    scheduler_list, scheduler_save, scheduler_toggle, scheduler_delete, scheduler_run_now, scheduler_dispatch_due,
    scheduler, settings_page, telegram_bots_manage, telegram_groups_manage,
    telegram_bot_studio, telegram_bot_studio_menus, telegram_bot_studio_menu_save, telegram_bot_studio_menu_delete, telegram_bot_studio_simulate,
    telegram_bot_studio_bot_save, telegram_bot_studio_set_webhook, telegram_bot_studio_webhook_info, telegram_bot_studio_delete_webhook,
    telegram_bot_webhook,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('yardim/', help_center, name='help_center'),
    path('robots/', robots, name='robots'),
    path('robot-control/', robot_control_center, name='robot_control_center'),
    path('processes/', processes, name='processes'),
    path('queues/', queues, name='queues'),
    path('scheduler/', scheduler, name='scheduler'),
    path('reports/', reports, name='reports'),
    path('settings/', settings_page, name='settings'),
    path('contacts/telegram-bots/', telegram_bots_manage, name='telegram_bots_manage'),
    path('contacts/telegram-groups/', telegram_groups_manage, name='telegram_groups_manage'),
    path('contacts/mail-accounts/', mail_accounts_manage, name='mail_accounts_manage'),
    path('contacts/ftp-accounts/', ftp_accounts_manage, name='ftp_accounts_manage'),
    path('sap-scan/', sap_scan, name='sap_scan'),
    path('sap-apply/', sap_apply, name='sap_apply'),
    path('sap-run/', sap_run, name='sap_run'),
    path('sap-template/list/', sap_template_list, name='sap_template_list'),
    path('sap-template/get/', sap_template_get, name='sap_template_get'),
    path('sap-template/save/', sap_template_save, name='sap_template_save'),
    path('sap-template/delete/', sap_template_delete, name='sap_template_delete'),
    path('sap-process/', sap_process_list, name='sap_process_list'),
    path('sap-process/<int:process_id>/', sap_process_builder, name='sap_process_builder'),
    path('sap-process/<int:process_id>/delete/', sap_process_delete, name='sap_process_delete'),
    path('sap-process/<int:process_id>/backup/', sap_process_backup, name='sap_process_backup'),
    path('sap-process/<int:process_id>/steps/save/', sap_process_step_save, name='sap_process_step_save'),
    path('sap-process/<int:process_id>/rename/', sap_process_rename, name='sap_process_rename'),
    path('sap-process/<int:process_id>/runtime-settings/', sap_process_runtime_settings_save, name='sap_process_runtime_settings_save'),
    path('sap-process/<int:process_id>/runtime-control/', sap_process_runtime_control, name='sap_process_runtime_control'),
    path('sap-process/<int:process_id>/runtime-status/', sap_process_runtime_status, name='sap_process_runtime_status'),
    path('sap-process/<int:process_id>/scan-buttons/', sap_process_scan_buttons, name='sap_process_scan_buttons'),
    path('sap-process/<int:process_id>/scan-selectables/', sap_process_scan_selectables, name='sap_process_scan_selectables'),
    path('sap-process/<int:process_id>/scan-inputs/', sap_process_scan_inputs, name='sap_process_scan_inputs'),
    path('sap-process/<int:process_id>/scan-windows-dialogs/', sap_process_scan_windows_dialogs, name='sap_process_scan_windows_dialogs'),
    path('sap-process/<int:process_id>/scan-screens/', sap_process_scan_screens, name='sap_process_scan_screens'),
    path('sap-process/<int:process_id>/scan-grids/', sap_process_scan_grids, name='sap_process_scan_grids'),
    path('sap-process/<int:process_id>/scan-popups/', sap_process_scan_popups, name='sap_process_scan_popups'),
    path('sap-process/<int:process_id>/excel-browse/', sap_process_excel_browse, name='sap_process_excel_browse'),
    path('sap-process/<int:process_id>/excel-sheets/', sap_process_excel_sheets, name='sap_process_excel_sheets'),
    path('sap-process/<int:process_id>/excel-columns/', sap_process_excel_columns, name='sap_process_excel_columns'),
    path('sap-process/<int:process_id>/run/', sap_process_run_preview, name='sap_process_run_preview'),
    path('telegram-studio/', telegram_bot_studio, name='telegram_bot_studio'),
    path('telegram-studio/menus/', telegram_bot_studio_menus, name='telegram_bot_studio_menus'),
    path('telegram-studio/menus/save/', telegram_bot_studio_menu_save, name='telegram_bot_studio_menu_save'),
    path('telegram-studio/menus/delete/', telegram_bot_studio_menu_delete, name='telegram_bot_studio_menu_delete'),
    path('telegram-studio/simulate/', telegram_bot_studio_simulate, name='telegram_bot_studio_simulate'),
    path('telegram-studio/bot-save/', telegram_bot_studio_bot_save, name='telegram_bot_studio_bot_save'),
    path('telegram-studio/webhook/set/', telegram_bot_studio_set_webhook, name='telegram_bot_studio_set_webhook'),
    path('telegram-studio/webhook/info/', telegram_bot_studio_webhook_info, name='telegram_bot_studio_webhook_info'),
    path('telegram-studio/webhook/delete/', telegram_bot_studio_delete_webhook, name='telegram_bot_studio_delete_webhook'),
    path('tg/webhook/<int:bot_id>/<str:secret>/', telegram_bot_webhook, name='telegram_bot_webhook'),
    path('api/help-media/upload/', help_media_upload, name='help_media_upload'),
    path('api/robot-agent/register/', agent_register, name='agent_register'),
    path('api/robot-agent/heartbeat/', agent_heartbeat, name='agent_heartbeat'),
    path('api/robot-agent/check-update/', agent_check_update, name='agent_check_update'),
    path('api/robot-agent/log-event/', agent_log_event, name='agent_log_event'),
    path('api/robot-agent/pull-job/', agent_pull_job, name='agent_pull_job'),
    path('api/robot-agent/job-update/', agent_job_update, name='agent_job_update'),
    path('api/robot-agent/process-definition/', agent_process_definition, name='agent_process_definition'),
    path('api/robot-agent/run-process/', agent_run_process, name='agent_run_process'),
    path('api/robot-agent/run-process-status/', agent_run_process_status, name='agent_run_process_status'),
    path('api/robot-agent/status/', robot_agent_status, name='robot_agent_status'),
    path('api/robot-agent/upsert/', robot_agent_upsert, name='robot_agent_upsert'),
    path('api/robot-agent/delete/', robot_agent_delete, name='robot_agent_delete'),
    path('api/robot-agent/events/', robot_agent_event_list, name='robot_agent_event_list'),
    path('api/robot-agent/jobs/', robot_job_list, name='robot_job_list'),
    path('api/robot-agent/cancel-job/', robot_cancel_job, name='robot_cancel_job'),
    path('api/robot-agent/dispatch-job/', robot_dispatch_job, name='robot_dispatch_job'),
    path('api/robot-agent/releases/', robot_release_list, name='robot_release_list'),
    path('api/robot-agent/releases/save/', robot_release_save, name='robot_release_save'),
    path('api/robot-agent/releases/download/<str:version>/', robot_release_download, name='robot_release_download'),
    path('api/robot-agent/releases/download-package/<str:version>/', robot_release_download_package, name='robot_release_download_package'),
    path('api/robot-agent/releases/build-setup/', robot_build_setup_exe, name='robot_build_setup_exe'),
    path('api/robot-agent/releases/build-package/', robot_build_install_package, name='robot_build_install_package'),
    path('api/robot-agent/releases/deploy/', robot_release_deploy, name='robot_release_deploy'),
    path('api/robot-agent/releases/set-desired/', robot_set_desired_version, name='robot_set_desired_version'),
    path('api/scheduler/list/', scheduler_list, name='scheduler_list'),
    path('api/scheduler/save/', scheduler_save, name='scheduler_save'),
    path('api/scheduler/toggle/', scheduler_toggle, name='scheduler_toggle'),
    path('api/scheduler/delete/', scheduler_delete, name='scheduler_delete'),
    path('api/scheduler/run-now/', scheduler_run_now, name='scheduler_run_now'),
    path('api/scheduler/dispatch-due/', scheduler_dispatch_due, name='scheduler_dispatch_due'),
]
