from django.urls import path

from .views import (
    dashboard, ftp_accounts_manage, mail_accounts_manage, processes, queues, reports, robots,
    sap_scan, sap_apply, sap_run,
    sap_template_list, sap_template_get, sap_template_save, sap_template_delete,
    sap_process_list, sap_process_builder, sap_process_delete,
    sap_process_step_save, sap_process_rename, sap_process_backup, sap_process_runtime_settings_save, sap_process_runtime_control, sap_process_runtime_status, sap_process_scan_buttons, sap_process_scan_selectables, sap_process_scan_inputs, sap_process_scan_windows_dialogs, sap_process_scan_screens, sap_process_scan_grids, sap_process_scan_popups, sap_process_excel_browse, sap_process_excel_sheets, sap_process_excel_columns, sap_process_run_preview,
    scheduler, settings_page, telegram_bots_manage, telegram_groups_manage,
    telegram_bot_studio, telegram_bot_studio_menus, telegram_bot_studio_menu_save, telegram_bot_studio_menu_delete, telegram_bot_studio_simulate,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('robots/', robots, name='robots'),
    path('processes/', processes, name='processes'),
    path('queues/', queues, name='queues'),
    path('scheduler/', scheduler, name='scheduler'),
    path('reports/', reports, name='reports'),
    path('settings/', settings_page, name='settings'),
    path('contacts/telegram-bots/', telegram_bots_manage, name='telegram_bots_manage'),
    path('contacts/telegram-groups/', telegram_groups_manage, name='telegram_groups_manage'),
    path('contacts/mail-accounts/', mail_accounts_manage, name='mail_accounts_manage'),
    path('contacts/ftp-accounts/', ftp_accounts_manage, name='ftp_accounts_manage'),
    path('sap-scan/', sap_scan, name='sap_scan'),
    path('sap-apply/', sap_apply, name='sap_apply'),
    path('sap-run/', sap_run, name='sap_run'),
    path('sap-template/list/', sap_template_list, name='sap_template_list'),
    path('sap-template/get/', sap_template_get, name='sap_template_get'),
    path('sap-template/save/', sap_template_save, name='sap_template_save'),
    path('sap-template/delete/', sap_template_delete, name='sap_template_delete'),
    path('sap-process/', sap_process_list, name='sap_process_list'),
    path('sap-process/<int:process_id>/', sap_process_builder, name='sap_process_builder'),
    path('sap-process/<int:process_id>/delete/', sap_process_delete, name='sap_process_delete'),
    path('sap-process/<int:process_id>/backup/', sap_process_backup, name='sap_process_backup'),
    path('sap-process/<int:process_id>/steps/save/', sap_process_step_save, name='sap_process_step_save'),
    path('sap-process/<int:process_id>/rename/', sap_process_rename, name='sap_process_rename'),
    path('sap-process/<int:process_id>/runtime-settings/', sap_process_runtime_settings_save, name='sap_process_runtime_settings_save'),
    path('sap-process/<int:process_id>/runtime-control/', sap_process_runtime_control, name='sap_process_runtime_control'),
    path('sap-process/<int:process_id>/runtime-status/', sap_process_runtime_status, name='sap_process_runtime_status'),
    path('sap-process/<int:process_id>/scan-buttons/', sap_process_scan_buttons, name='sap_process_scan_buttons'),
    path('sap-process/<int:process_id>/scan-selectables/', sap_process_scan_selectables, name='sap_process_scan_selectables'),
    path('sap-process/<int:process_id>/scan-inputs/', sap_process_scan_inputs, name='sap_process_scan_inputs'),
    path('sap-process/<int:process_id>/scan-windows-dialogs/', sap_process_scan_windows_dialogs, name='sap_process_scan_windows_dialogs'),
    path('sap-process/<int:process_id>/scan-screens/', sap_process_scan_screens, name='sap_process_scan_screens'),
    path('sap-process/<int:process_id>/scan-grids/', sap_process_scan_grids, name='sap_process_scan_grids'),
    path('sap-process/<int:process_id>/scan-popups/', sap_process_scan_popups, name='sap_process_scan_popups'),
    path('sap-process/<int:process_id>/excel-browse/', sap_process_excel_browse, name='sap_process_excel_browse'),
    path('sap-process/<int:process_id>/excel-sheets/', sap_process_excel_sheets, name='sap_process_excel_sheets'),
    path('sap-process/<int:process_id>/excel-columns/', sap_process_excel_columns, name='sap_process_excel_columns'),
    path('sap-process/<int:process_id>/run/', sap_process_run_preview, name='sap_process_run_preview'),
    path('telegram-studio/', telegram_bot_studio, name='telegram_bot_studio'),
    path('telegram-studio/menus/', telegram_bot_studio_menus, name='telegram_bot_studio_menus'),
    path('telegram-studio/menus/save/', telegram_bot_studio_menu_save, name='telegram_bot_studio_menu_save'),
    path('telegram-studio/menus/delete/', telegram_bot_studio_menu_delete, name='telegram_bot_studio_menu_delete'),
    path('telegram-studio/simulate/', telegram_bot_studio_simulate, name='telegram_bot_studio_simulate'),
]
