"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g+l)da@c*mn*k==$e2qj#+v+=c@^xgcs-^+bvc&%a5peuz!zdv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Firebase Configuration
import firebase_admin
from firebase_admin import credentials, db

FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'config' / 'firebase-key.json'

try:
    if not firebase_admin._apps:
        cred = credentials.Certificate(str(FIREBASE_CREDENTIALS_PATH))
        project_id = None
        try:
            import json
            with open(FIREBASE_CREDENTIALS_PATH, 'r', encoding='utf-8') as fp:
                project_id = (json.load(fp) or {}).get('project_id')
        except Exception:
            project_id = 'saggiorpa'

        preferred_url = os.getenv(
            'FIREBASE_DATABASE_URL',
            f'https://{project_id}-default-rtdb.europe-west1.firebasedatabase.app',
        ).strip()

        # RTDB bu projede europe-west1 bolgesinde. Yine de fallback adaylari tutuluyor.
        candidates = [
            preferred_url,
            f'https://{project_id}-default-rtdb.europe-west1.firebasedatabase.app',
            f'https://{project_id}-default-rtdb.firebaseio.com',
            f'https://{project_id}-default-rtdb.us-central1.firebasedatabase.app',
        ]
        # Sira korunarak duplicate URL'leri kaldir.
        candidates = list(dict.fromkeys([u for u in candidates if u]))

        init_ok = False
        last_error = None
        for url in candidates:
            app = None
            try:
                app = firebase_admin.initialize_app(cred, {'databaseURL': url})
                # URL dogrulamasi: 404 verirse bir sonraki adrese gec.
                db.reference('/', app=app).get()
                init_ok = True
                break
            except Exception as ex:
                last_error = ex
                if app is not None:
                    try:
                        firebase_admin.delete_app(app)
                    except Exception:
                        pass
                continue

        if not init_ok and last_error:
            raise last_error
except Exception as e:
    print(f"Firebase initialization error: {e}")
